<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_ref_gaji_model extends CI_Model
{

    public $table = 'tbl_ref_gaji';
    public $id = 'id_ref_gaji';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    
    function json(){
        $this->db->select('tbl_ref_gaji.*, tbl_ref_gaji.id_ref_gaji, tbl_jabatan.nama_jabatan');
        $this->db->from('tbl_ref_gaji');
        $this->db->join('tbl_jabatan', 'tbl_jabatan.id_jabatan=tbl_ref_gaji.id_jabatan');
        //$this->db->add_column('action', anchor(site_url('hrms/ref_gaji/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>','class="btn btn-success btn-sm"')." 
          //      ".anchor(site_url('hrms/ref_gaji/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_ref_gaji');
        // if ($id_klinik != null) {
        //     $this->db->where('tbl_pegawai.id_klinik', $id_klinik);
        // }
        return $this->db->get()->result();
    }
    function get_by_jabatan($id)
    {
        $this->db->where('id_jabatan', $id);
        return $this->db->get($this->table)->row();
    }

}

/* End of file Tbl_pasien_model.php */
/* Location: ./application/models/Tbl_pasien_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-03 15:02:10 */
/* http://harviacode.com */