<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Shift extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('hrms/Tbl_shift_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
        $this->id_klinik = $this->session->userdata('id_klinik');
    }

    public function index()
    {
        $this->template->load('template','hrms/shift/tbl_shift_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbl_shift_model->json();
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('hrms/shift/create_action'),
    	    'id_shift' => set_value('id_shift'),
    	    'nama_shift' => set_value('nama_shift'),
            'jam_datang' => set_value('jam_datang'),
            'jam_pulang' => set_value('jam_pulang'),
	);
        $this->template->load('template','hrms/shift/tbl_shift_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();
        
        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'nama_shift' => $this->input->post('nama_shift',TRUE),
                'jam_datang' => $this->input->post('jam_datang',TRUE),
                'jam_pulang' => $this->input->post('jam_pulang',TRUE),
                'id_klinik' => $this->id_klinik,
        );
            $insert=$this->Tbl_shift_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('hrms/shift'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbl_shift_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('hrms/shift/update_action'),
                'id_shift' => set_value('id_shift', $row->id_shift),
                'nama_shift' => set_value('nama_shift', $row->nama_shift),
                'jam_datang' => set_value('jam_datang', $row->jam_datang),
                'jam_pulang' => set_value('jam_pulang', $row->jam_pulang),
	    );
            $this->template->load('template','hrms/shift/tbl_shift_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('hrms/shift'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_shift', TRUE));
        } else {
            $data = array(
        		'nama_shift' => $this->input->post('nama_shift',TRUE),
                'jam_datang' => $this->input->post('jam_datang',TRUE),
                'jam_pulang' => $this->input->post('jam_pulang',TRUE),
                'dtm_upd' => date("Y-m-d H:i:s",  time())
	    );

            $this->Tbl_shift_model->update($this->input->post('id_shift', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('hrms/shift'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbl_shift_model->get_by_id($id);

        if ($row) {
            $this->Tbl_shift_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('hrms/shift'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('hrms/shift'));
        }
    }

    public function _rules() 
    {
        
    $this->form_validation->set_rules('id_shift', 'id shift', 'trim');
	$this->form_validation->set_rules('nama_shift', 'nama shift', 'trim|required');
    $this->form_validation->set_rules('jam_datang', 'jam_datang', 'trim|required');
	$this->form_validation->set_rules('jam_pulang', 'jam_pulang', 'trim|required');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
    

}

/* End of file shift.php */
/* Location: ./application/controllers/shift.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-27 18:45:56 */
/* http://harviacode.com */